global:
  qsname: quickstart-enterprise-accelerator-msservers
  owner: quickstart@amazon.com
  marketplace-ami: false
  reporting: true
  cis3bucket: s3://quickstart-ci-bucket
  prod-s3-path: s3://quickstart-reference/enterprise-accelerator/msservers
  regions:
    - ap-northeast-1
#    - ap-northeast-2 NAT Gateway not available
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
#    - sa-east-1 NAT Gateway not available
    - us-east-1
    - us-west-1
    - us-west-2
tests:
  master:
    template_file: msservers-master.template
    parameter_input: msservers-master.json
